### ISSUE TITLE
Labelisation

### ISSUE THREAD

**Issue by kamil-bentounes** [aamirfaaiz/Synthetic-Voice-Detection#1]
Hey !

thanks for sharing the project. My question is about the data labelisation. I read the dataset documentation and your readme but anywhere I found if '0' means Speech or '1' ?

Thanks

**Comment by mendaxfz** [comment]
Hey!

Thank you for your message, real speech would be labelled as '1' and synthetic/deepfake speech would be labelled as '0'

Best
